name: Event Filters
on:
  push:
    branches:
      - dev
      - 'release/*'
    paths-ignore:
      - 'docs/**'

jobs:
  test-filters:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch & event
        run: echo "Event filters working! Triggered on ${{ github.ref_name }} (event=${{ github.event_name }})"
